version: '3'
services:
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
  metabase:
    image: metabase/metabase
    ports:
        - "3000:3000"
  exporter:
    image: scenedoc/exporter
    depends_on:
        - metabase
        - mongo
    environment:
        - MONGO_HOST=mongo
        - API_KEY=
        - API_SECRET_KEY=
        - URL=